# Generated by Django 5.1.3 on 2024-11-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="price",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
